### ISSUE TITLE
Oddity with Pandas and Planck spectra blog post

### ISSUE THREAD

**Issue by mpeel** [zonca/zonca-blog#19]
Hi Andrea, with this blog post:
https://github.com/zonca/zonca-blog/blob/master/_notebooks/2020-09-30-planck-spectra-healpy.ipynb

There seems to be an issue now with the line:
```
input_cl = pd.read_csv("COM_PowerSpect_CMB-base-plikHM-TTTEEE-lowl-lowE-lensing-minimum-theory_R3.01.txt",
                       delim_whitespace=True, index_col=0)
```
When you run this now, then the first column, which should be 'TT', ends up as 'L':
![image](https://user-images.githubusercontent.com/710707/159526488-de73d8f3-9b23-4ab4-9ad5-f23e350e72a8.png)

A student of mine was trying to follow the example, and ran into this problem. I don't use Pandas so I don't know what the correct solution is. Thought I should mention it here for anyone else following the same tutorial!

**Comment by zonca** [comment]
yes, just in the cell above it says

`pandas` has trouble with the `#` at the beginning of the title line, the easiest is to edit that out with a file editor.

**Comment by mpeel** [comment]
Aah, thanks, just running the !head command doesn't do that - you have to manually edit it, then it works. Thanks, and sorry for missing that!
